<?php
//include("blocked.php");
include("config.php");
include("core.php");
header("Cache-Control: no-cache, must-revalidate");	        // Prevent caching, HTTP/1.1
header("Pragma: no-cache");
?>
<?php
$bcon = connectdb();
if (!$bcon)
{
    echo "<head>";
    echo "<title>Error!!!</title>";
    echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"../themes/white_medium.css\">";
    echo "</head>";
    echo "<body>";
    echo "<p align=\"center\">";
    echo "<img src=\"../images/notok.gif\" alt=\"!\"/><br/>";
    echo "<b><strong>Error! Cannot Connect To Database...</strong></b><br/><br/>";
    echo "This error happens usually when backing up the database, please be patient...";
    echo "</p>";
    echo "</body>";
    echo "</html>";
    exit();
}
echo "<!DOCTYPE html>\n"; 
echo "<html dir=\"ltr\" lang=\"en-US\"><head><!-- Created by Artisteer v4.1.0.60046 -->\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <title>Home</title>\n"; 
echo "    <meta name=\"viewport\" content=\"initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width\">\n"; 
echo "\n"; 
echo "    <!--[if lt IE 9]><script src=\"https://html5shiv.googlecode.com/svn/trunk/html5.js\"></script><![endif]-->\n"; 
echo "    <link rel=\"stylesheet\" href=\"style.css\" media=\"screen\">\n"; 
echo "    <!--[if lte IE 7]><link rel=\"stylesheet\" href=\"style.ie7.css\" media=\"screen\" /><![endif]-->\n"; 
echo "    <link rel=\"stylesheet\" href=\"style.responsive.css\" media=\"all\">\n"; 
echo "\n"; 
echo "\n"; 
echo "    <script src=\"jquery.js\"></script>\n"; 
echo "    <script src=\"script.js\"></script>\n"; 
echo "    <script src=\"script.responsive.js\"></script>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<style>.art-content .art-postcontent-0 .layout-item-0 { padding-right: 10px;padding-left: 10px;  }\n"; 
echo ".ie7 .art-post .art-layout-cell {border:none !important; padding:0 !important; }\n"; 
echo ".ie6 .art-post .art-layout-cell {border:none !important; padding:0 !important; }\n"; 
echo "\n"; 
echo "</style></head>\n"; 
echo "<body>\n"; 
echo "<div id=\"art-main\">\n"; 
echo "    <div class=\"art-sheet clearfix\">\n"; 
echo "<header class=\"art-header\">\n"; 
echo "\n"; 
echo "    <div class=\"art-shapes\">\n"; 
echo "        \n"; 
echo "            </div>\n"; 
echo "<div class=\"art-slider art-slidecontainerheader\" data-width=\"800\" data-height=\"110\">\n"; 
echo "    <div class=\"art-slider-inner\">\n"; 
echo "<a class=\"art-slide-item art-slideheader0\">\n"; 
echo "\n"; 
echo "</a>\n"; 
echo "<a class=\"art-slide-item art-slideheader1\">\n"; 
echo "\n"; 
echo "</a>\n"; 
echo "\n"; 
echo "    </div>\n"; 
echo "</div>\n"; 
echo "<div class=\"art-slidenavigator art-slidenavigatorheader\" data-left=\"94.5\">\n"; 
echo "<a href=\"#\" class=\"art-slidenavigatoritem\"></a><a href=\"#\" class=\"art-slidenavigatoritem\"></a>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "\n"; 
echo "<h1 class=\"art-headline\" data-left=\"1.23%\">\n"; 
echo "    <a href=\"#\">MahmudulMaruf</a>\n"; 
echo "</h1>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<div class=\"art-textblock art-object227400126\" data-left=\"97.5%\">\n"; 
echo "    <form class=\"art-search\" name=\"Search\" action=\"javascript:void(0)\">\n"; 
echo "    <input type=\"text\" value=\"\">\n"; 
echo "    <input type=\"submit\" value=\"Search\" name=\"search\" class=\"art-search-button\">\n"; 
echo "</form>\n"; 
echo "</div>\n"; 
echo "<nav class=\"art-nav\">\n"; 
echo "    <ul class=\"art-hmenu\"><li><a href=\"home.html\" class=\"active\">Home</a></li><li><a href=\"my-profile.html\">My Profile</a></li><li><a href=\"programming.html\">Programming</a><ul><li><a href=\"programming/c.html\">C</a></li><li><a href=\"programming/c-2.html\">C++</a></li><li><a href=\"programming/java.html\">JAVA</a></li><li><a href=\"programming/python.html\">Python</a></li></ul></li><li><a href=\"projects.html\">Projects</a></li><li><a href=\"papers.html\">Papers</a></li><li><a href=\"download-hub.html\">Download Hub</a><ul><li><a href=\"download-hub/books.html\">Books</a><ul><li><a href=\"download-hub/books/engineering-books.html\">Engineering Books</a></li><li><a href=\"download-hub/books/mathematics.html\">Mathematics</a></li></ul></li><li><a href=\"download-hub/android.html\">Android</a><ul><li><a href=\"download-hub/android/games.html\">Games</a></li><li><a href=\"download-hub/android/tools.html\">Tools</a></li><li><a href=\"download-hub/android/daily-life-apps.html\">Daily life Apps</a></li></ul></li><li><a href=\"download-hub/windows.html\">Windows</a></li><li><a href=\"download-hub/others.html\">Others</a></li><li><a href=\"download-hub/youtube.html\">Youtube</a></li></ul></li></ul> \n"; 
echo "    </nav>\n"; 
echo "\n"; 
echo "                    \n"; 
echo "</header>\n"; 
echo "<div class=\"art-layout-wrapper\">\n"; 
echo "                <div class=\"art-content-layout\">\n"; 
echo "                    <div class=\"art-content-layout-row\">\n"; 
echo "                        <div class=\"art-layout-cell art-sidebar1\"><div class=\"art-vmenublock clearfix\">\n"; 
echo "        <div class=\"art-vmenublockheader\">\n"; 
echo "            <h3 class=\"t\">Menu</h3>\n"; 
echo "        </div>\n"; 
echo "        <div class=\"art-vmenublockcontent\">\n"; 
echo "<ul class=\"art-vmenu\"><li><a href=\"home.html\" class=\"active\">Home</a></li><li><a href=\"my-profile.html\">My Profile</a></li><li><a href=\"programming.html\">Programming</a><ul><li><a href=\"programming/c.html\">C</a></li><li><a href=\"programming/c-2.html\">C++</a></li><li><a href=\"programming/java.html\">JAVA</a></li><li><a href=\"programming/python.html\">Python</a></li></ul></li><li><a href=\"projects.html\">Projects</a></li><li><a href=\"papers.html\">Papers</a></li><li><a href=\"download-hub.html\">Download Hub</a><ul><li><a href=\"download-hub/books.html\">Books</a><ul><li><a href=\"download-hub/books/engineering-books.html\">Engineering Books</a></li><li><a href=\"download-hub/books/mathematics.html\">Mathematics</a></li></ul></li><li><a href=\"download-hub/android.html\">Android</a><ul><li><a href=\"download-hub/android/games.html\">Games</a></li><li><a href=\"download-hub/android/tools.html\">Tools</a></li><li><a href=\"download-hub/android/daily-life-apps.html\">Daily life Apps</a></li></ul></li><li><a href=\"download-hub/windows.html\">Windows</a></li><li><a href=\"download-hub/others.html\">Others</a></li><li><a href=\"download-hub/youtube.html\">Youtube</a></li></ul></li></ul>\n"; 
echo "                \n"; 
echo "        </div>\n"; 
echo "</div><div class=\"art-block clearfix\">\n"; 
echo "        <div class=\"art-blockheader\">\n"; 
echo "            <h3 class=\"t\">Block</h3>\n"; 
echo "        </div>\n"; 
echo "        <div class=\"art-blockcontent\"><p>Enter Block content here...</p>\n"; 
echo "<br>\n"; 
echo "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pharetra, tellus sit amet congue vulputate, nisi erat iaculis nibh, vitae feugiat sapien ante eget mauris.</p></div>\n"; 
echo "</div></div>\n"; 
echo "                        <div class=\"art-layout-cell art-content\"><article class=\"art-post art-article\">\n"; 
echo "                                <h2 class=\"art-postheader\">Home</h2>\n"; 
echo "                                                \n"; 
echo "                <div class=\"art-postcontent art-postcontent-0 clearfix\"><div class=\"art-content-layout\">\n"; 
echo "    <div class=\"art-content-layout-row\">\n"; 
echo "    <div class=\"art-layout-cell layout-item-0\" style=\"width: 100%\" >\n"; 
echo "        <div class=\"image-caption-wrapper\" style=\"width: 55%; float: left\"><img alt=\"an image\" style=\"width: 100%; max-width: 420px; \" class=\"art-lightbox\" src=\"images/79.jpg\"></div>\n"; 
echo "        <p>Md. Mahmudul Haque Maruf</p>\n"; 
echo "        <p>B.Sc. in Computer Science & Engineering. Love programming though not a good programmer myself.</p>\n"; 
echo "        <p><a href=\"#\">Read more</a></p>\n"; 
echo "    </div>\n"; 
echo "    </div>\n"; 
echo "</div>\n"; 
echo "<div class=\"art-content-layout\">\n"; 
echo "    <div class=\"art-content-layout-row\">\n"; 
echo "    <div class=\"art-layout-cell layout-item-0\" style=\"width: 50%\" >\n"; 
echo "        <ul>\n"; 
echo "        <li>Suspendisse pharetra auctor pharetra. Nunc a sollicitudin est.</li>\n"; 
echo "        <li>Donec vel neque in neque porta venenatis sed sit amet lectus.</li>\n"; 
echo "        <li>Curabitur ullamcorper gravida felis, sit amet scelerisque lorem iaculis sed.</li>\n"; 
echo "        </ul>\n"; 
echo "    </div><div class=\"art-layout-cell layout-item-0\" style=\"width: 50%\" >\n"; 
echo "        <blockquote style=\"margin: 10px 0\">Nunc a sollicitudin est. Curabitur ullamcorper gravida felis, sit amet scelerisque lorem iaculis sed. Donec vel neque in neque porta venenatis sed sit amet lectus.</blockquote>\n"; 
echo "    </div>\n"; 
echo "    </div>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "\n"; 
echo "</article></div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div><footer class=\"art-footer\">\n"; 
echo "			\n"; 
echo "<p><a href=\"http://mahmudulmaaruf.com\">Home</a> | <a href=\"contact.html\">Contact</a> | <a href=\"desclaimer.html\">Disclaimer</a></p>\n"; 
echo "<p color=\"white\">&copy;MahmudulMaruf.Com</p>\n"; 
echo "</footer>\n"; 
echo "\n"; 
echo "    </div>\n"; 
echo "	<p class=\"art-page-footer\">Copyright &copy 2017. All Rights Reserved.</p>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "\n"; 
echo "</body></html>\n";
?>